import temp
import numpy as np
import matplotlib.pyplot as plt

N = 4
numt = np.arange(1, N+1)
AllEMG = np.empty(N)
MNF = np.empty(N)
MDF = np.empty(N)
slowrate = np.empty(N)

print("----------------------------------")
AllEMG[0], MNF[0], MDF[0], slowrate[0] = temp.temp("01_002.csv")
print("----------------------------------")
AllEMG[1], MNF[1], MDF[1], slowrate[1] = temp.temp("01_003.csv")
print("----------------------------------")
AllEMG[2], MNF[2], MDF[2], slowrate[2] = temp.temp("01_004.csv")
print("----------------------------------")
AllEMG[3], MNF[3], MDF[3], slowrate[3] = temp.temp("01_005.csv")
print("----------------------------------")
# AllEMG[4], MNF[4], MDF[4], slowrate[4] = temp.temp("231026/1255.csv")
# print("----------------------------------")
# AllEMG[5], MNF[5], MDF[5], slowrate[5] = temp.temp("231026/1256.csv")
# print("----------------------------------")
# AllEMG[6], MNF[6], MDF[6], slowrate[6] = temp.temp("231026/1258.csv")
# print("----------------------------------")
# AllEMG[7], MNF[7], MDF[7], slowrate[7] = temp.temp("231026/1259.csv")
# print("----------------------------------")
# AllEMG[8], MNF[8], MDF[8], slowrate[8] = temp.temp("231026/1300.csv")
# print("----------------------------------")
# AllEMG[9], MNF[9], MDF[9], slowrate[9] = temp.temp("231026/1302.csv")
# print("----------------------------------")

plt.plot(numt, AllEMG)
plt.grid(True)
plt.xlabel("number of times")
plt.ylabel("iEMG[mV s]")
plt.xticks(numt)
plt.show()

plt.plot(numt, MNF, label="MNF")
plt.plot(numt, MDF, label="MDF")
plt.grid(True)
plt.xlabel("number of times")
plt.ylabel("frequency[Hz]")
plt.xticks(numt)
plt.legend()
plt.show()

plt.plot(numt, slowrate*100)
plt.grid(True)
plt.xlabel("number of times")
plt.ylabel("rate[%]")
plt.xticks(numt)
plt.show()